
server:
  port: 5001

spring:
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/userService
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa:
  #   show-sql: true
